### ISSUE TITLE
Add a dual to the assignContext() method

### ISSUE THREAD

**Issue by djalbat** [djalbat/juxtapose#3]
Whether this works really depends on the way in which the `assignContext()` method works. At the moment, typically it is called in the `parentContext()` method rather than the `appendTo()` method, for example. If we want something along similar lines to the symmetry that is possible with reaction, this may need a rethink.

**Comment by ghost** [comment]
The `updateContext()` method is called from the `addTo()`, etc methods in the JSX mixin. So a dual method called from the `removeFrom()` method seems to be what's called for. And it does not seem unreasonable that the `assignContext()` method be called from within the `addTo()` etc methods because the context on the element in question has already been defined. It is used in the `updateParentContext()` method, after all.

**Comment by ghost** [comment]
This closed issue is the one: https://github.com/occam-proof-assistant/Occam/issues/132

**Comment by djalbat** [comment]
This can't be done, unfortunately. However, things have been simplified.
